steps:
  - name: ubuntu
    args:
      - bash
      - '-c'
      - echo '$COMMIT_SHA' > REVISION.txt
  - name: gcr.io/cloud-builders/syncutil
    args:
      - '-m'
      - rsync
      - '-d'
      - '-r'
      - dags
      - 'gs://us-central1-beta-airflow-0cf0226f-bucket/dags'
